### ISSUE TITLE
Refresh Sitemap Cache results in a 404 error

### ISSUE THREAD

**Issue by Dubbsman** [webadvanced/Orchard-SiteMap#12]
I wend back to 1.4 and confirmed this issue is only in 1.5.
## Server Error in '/' Application.

The resource cannot be found. 
  Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

 Requested URL: /Admin/WebAdvanced.Sitemap/RefreshXmlCache

**Comment by CPyle** [comment]
This has been fixed in the newest version, it will be up by end of day.
