### ISSUE TITLE
Sitemap.xml delayed update

### ISSUE THREAD

**Issue by Levitikon217** [webadvanced/Orchard-SiteMap#2]
I noticed the sitemap.xml doesn't automatically get updated when new pages are added or the url to existing pages are modified. When creating a few tenant sites and then coming back to look at the sitemap.xml for all of them, the ones that are a few hours old have accurate sitemap.xmls, but the newest sites created only minutes before do not reflect an accurate sitemap. They always have just the single root path. It takes me disabling the module, then re-enabling it to refresh. Using In Orchard 1.4.2.

For instance, when I create 10 tenant sites and each site takes 30 minutes to setup. When they're all setup and I check the sitemap.xml for each tenant, they all show all the pages except that last tenant which only shows the single root site path, for which I have to disable and re-enable. This is a regular pattern I run into.

**Comment by CPyle** [comment]
The sitemap.xml contents are generated and cached daily. There isn't a setting right now to adjust this but I may decrease the time in future versions or expose it as a setting.

**Comment by sl1m3d** [comment]
How about adding a simple button to refresh the sitemap?
