### ISSUE TITLE
Sitemap.xml only updates after app restart

### ISSUE THREAD

**Issue by Piedone** [webadvanced/Orchard-SiteMap#3]
Not after settings or content is updated.

**Comment by CPyle** [comment]
The xml is set to be cached daily. This has been causing some confusion so I'll probably switch it over to using the same policy as the sitemap display page, which behaves as you would expect.

**Comment by Piedone** [comment]
OK, that makes sense. This is fine in itself, but I'd definitely indicate this somewhere on the admin screen, with the option of clearing the cache immediately.

**Comment by CPyle** [comment]
Addressed in 1.4.0 release.
